"""empty message

Revision ID: 560de71e6f64
Revises: 6e17caf78a33
Create Date: 2022-01-21 14:22:31.525926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560de71e6f64'
down_revision = '6e17caf78a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_ibfk_1', 'user', 'queue_number', ['id'], ['id'])
    # ### end Alembic commands ###
