"""empty message

Revision ID: 6b25746abf76
Revises: 51d5c237b35b
Create Date: 2022-01-21 13:37:31.175015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b25746abf76'
down_revision = '51d5c237b35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'queue_number', 'user', ['id'], ['id'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_ibfk_1', 'user', 'queue_number', ['id'], ['id'])
    op.drop_constraint(None, 'queue_number', type_='foreignkey')
    # ### end Alembic commands ###
