"""empty message

Revision ID: 845ee7730152
Revises: 6b25746abf76
Create Date: 2022-01-21 13:38:44.363235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845ee7730152'
down_revision = '6b25746abf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('queue_number_ibfk_1', 'queue_number', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'queue_number', ['id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('queue_number_ibfk_1', 'queue_number', 'user', ['id'], ['id'])
    # ### end Alembic commands ###
